### PR TITLE
Add support for tags in CheckResponse

### PR DESCRIPTION
**Pull request by cryptobioz**

### CODE REVIEW

**Comment by partamonov** [comment]
Hello @cryptobioz when do you plan to merge tags support?

**Comment by partamonov** [comment]
Also you need to modify 
```go
func (cs *CheckService) List() ([]CheckResponse, error) {
         params := make(map[string]string)
	params["include_tags"] = "true"

	req, err := cs.client.NewRequest("GET", "/api/2.1/checks", params)
```

**Comment by russellcardullo** [comment]
Thanks for the PR @cryptobioz !  I can merge this now.  

@partamonov did you want to open another PR with your suggestion about adding `include_tags` to `List()`?  If not I should have some time to put out something tomorrow for that.

**Comment by partamonov** [comment]
@russellcardullo I will, now doing maintenances part and will create PR for it.

**Pull request merged**
