### PR TITLE
Allow creation, update, and retrieval of SSL certificate options

### PR DESCRIPTION
**Pull request by justincmoy**
Addresses https://github.com/russellcardullo/terraform-provider-pingdom/issues/69 in underlying library

### CODE REVIEW

**Comment by justincmoy** [comment]
Looks like this passed the build but didn't leave a mark on the PR: https://travis-ci.org/github/russellcardullo/go-pingdom/builds/710892067

@russellcardullo thoughts on the note about the backwards-incompatibility of the VerifyCertificate bool?

**Comment by russellcardullo** [comment]
@justincmoy yeah the default of false breaking the server default of true for VerifyCertificate on the API for Pingdom isn't ideal for how we have the library today.  I think that would cause people using this to have their checks unknowingly changed.

Ideally what we better I think is if we have all the optional params be  `*bool, *int` etc instead of `bool, int`.  That would simplify some of the handling we have in places like this: https://github.com/russellcardullo/go-pingdom/blob/master/pingdom/check_types.go#L107-L113.  Then when sending the request we'd avoid serializing items that aren't set which would let them get their default value.

Maybe since these are new params, did you want to try using `*bool` and `*int`?  Eventually I'd like to change the other optional params but we can start with just the new ones you have here?

**Comment by justincmoy** [comment]
@russellcardullo That sounds good to me. I've pushed up a commit to this PR and updated the tests for both behaviors.

**Review by russellcardullo — APPROVED** [review]
Thanks @justincmoy!.  This LGTM!

**Pull request merged**
